# -*- coding: utf-8 -*-
"""automate_I-Gede-Made-Widi-Anditya

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z4PmbZEi_67MBIuQhPNvr7obKBYIqLIg
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler
import os

def run_automation():
    # Menentukan jalur file sesuai standar struktur
    input_file = 'namadataset_raw/heart.csv'
    output_dir = 'preprocessing/namadataset_preprocessing'

    # Membuat folder output jika belum ada
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # 1. Memuat Dataset
    if os.path.exists(input_file):
        df = pd.read_csv(input_file)
    else:
        print(f"Error: File {input_file} tidak ditemukan!")
        return

    # 2. Preprocessing: Menghapus Duplikat & Standarisasi
    df = df.drop_duplicates()

    scaler = StandardScaler()
    num_cols = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
    df[num_cols] = scaler.fit_transform(df[num_cols])

    # 3. Menyimpan dataset bersih
    output_path = f"{output_dir}/cleaned_heart.csv"
    df.to_csv(output_path, index=False)
    print(f"Otomatisasi Berhasil! Dataset disimpan di: {output_path}")

if __name__ == "__main__":
    run_automation()