name: Heart Preprocessing Advance

on:
  push:
    branches: [ "main" ] # Gunakan ini agar setiap push memicu workflow

jobs:
  preprocess_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'
      - name: Install dependencies
        run: pip install pandas scikit-learn
      - name: Check Folder Structure
        run: ls -R  # menampilkan semua file di log Actions
      - name: Run automation
        run: python preprocessing/automate_i-gede-made-widi-anditya.py 